<div class="container-fluid main-content">
		 <div class="invoice">
          <div class="row">
            <div class="col-lg-12">
                <div class="well">
                  <strong>网站信息</strong>
					<h6>
					Rubeus
					</h6>
					<p>
					项目做了一次升级，原版是名字叫做汉乐府，由于部分地方加载速度慢，所以从新做了规划，由原来的CodeIgniter框架为基础开发的项目。改为Yaf框架。
					</p>
                </div>
            </div>
          </div>
		  
		   <div class="row">
            <div class="col-lg-12">
                <div class="well">
                  <strong>我的信息</strong>
					<h6>
					  2013rain
					</h6>
					<p>
					  2013年毕业于河南大学<br>网络工程专业<br>
					  2010年开始接触php，2011年学习zendframe框架，熟悉mvc结构，熟悉ci、thinkphp框架,熟悉linux基本命令。<br>
					  2012年8月-2014年8月 在西街网参与开放erp系统并维护有关淘宝信息对接内容。<br>
					  2014年8月在百度文学担任php前端工程师。
					  2015年12月自己学习nodejs，并用thinkjs自己开发了个简单的系统(cf.wangfuyu.com.cn)。
					</p>
					<p>
					<a href="mailto:admin@wangfuyu.com.cn">admin@wangfuyu.com.cn</a>
					</p>
					
                </div>
            </div>
          </div>
		</div>
</div>
