<div class="container">
 <div class="row">
        <div class="col-sm-12 blog-main">
<!-- 多说评论框 start -->
	<div class="ds-thread" data-thread-key="<?php echo  $tplVars['id'];?>" data-title="<?php echo  $tplVars['title']; ?>" data-image="http://image.wangfuyu.com.cn/wangfuyu_400.jpg"  data-url=""></div>
<!-- 多说评论框 end -->
<!-- 多说公共JS代码 start (一个网页只需插入一次) -->
<script type="text/javascript">
var duoshuoQuery = {short_name:"rubeus"};
	(function() {
		var ds = document.createElement('script');
		ds.type = 'text/javascript';ds.async = true;
		ds.src = (document.location.protocol == 'https:' ? 'https:' : 'http:') + '//static.duoshuo.com/embed.js';
		ds.charset = 'UTF-8';
		(document.getElementsByTagName('head')[0] 
		 || document.getElementsByTagName('body')[0]).appendChild(ds);
	})();
	</script>
<!-- 多说公共JS代码 end -->
	</div>
</div>
</div>
